Allow uppercase chars in Shared Folder name
NethServer/nethserver-ibays pull request #17
Opened 2017-03-14 15:58 UTC by SebastianMB-IT

The username validator is too restrictive, removed completely.

2017-03-14 16:20 UTC, gsanchietti commented
In-progress...

2017-03-14 16:20 UTC, gsanchietti requested changes
This PR is still in progress.

2017-03-22 09:59 UTC, DavidePrincipi requested changes

2017-03-22 09:59 UTC, DavidePrincipi commented on root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_SharedFolder.php
> +$L['valid_platform,ibay-validator,ibay-name,3'] = 'The following characters are not allowed \ / : * ? " < > |';
The label key must be fixed: ``valid_platform,ibay-create,ibay-name,3`` (``validator`` becomes ``create``).

2017-03-22 10:42 UTC, DavidePrincipi approved these changes

2017-03-22 13:17 UTC, gsanchietti approved these changes

2017-03-22 13:17 UTC, gsanchietti commented on createlinks
> +				  ibay-name 20
Please correctly indent this line.

2017-03-22 13:17 UTC, gsanchietti commented on root/etc/e-smith/validators/actions/ibay-name
> +# Copyright (C) 2012 Nethesis S.r.l.
Change the year to 2017.

2017-03-22 13:18 UTC, merged